version: '3.0'

services:
  sparql:
    build: 
      context: .
      dockerfile: Dockerfile
    image: virtuoso
    environment:
      DBA_PASSWORD : pass
      VIRT_PARAMETERS_DIRSALLOWED : ., ../vad, /usr/share/proj, /import
    ports:
      - "8890:8890"
      - "1111:1111"
    volumes:
      - virtuoso-database:/database:rw
      - ./n3:/import:ro

volumes:
  virtuoso-database:
