export type Artist = {
    name : string,
    type : string,
    uris : Map<string, string>,
    image : string,
    birth_date : Date,
    birth_place : string,
    death_date : Date | null,
    death_place : string | null,
    death_manner : string | null,
    biography : Map<string, string>,
    getty_link : string,
    movements : string[],
    wikipedia_link: string,
    artworks : string[],
}